file = open('output.txt', 'w')
data = input("Enter the data to be written in file:")
file.write(data + '\n')
file.close()
print("Data successfully written to output.txt")
file = open('output.txt', 'a')
append_data = input("Enter additional data to append:")
file.write(append_data + '\n')
file.close()
print("Data successfully appneded.")
file = open('output.txt', 'r')
read_file = file.read()
print(read_file)
file.close()